# Generated by Django 3.2.14 on 2022-11-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0002_auto_20221126_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='state',
            field=models.CharField(default='order', max_length=20, verbose_name='state'),
        ),
    ]
